# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest
container: cypress/browsers:latest #use latest, not version number

steps:
- script: |
    npm ci --legacy-peer-deps
    npm install mochawesome --legacy-peer-deps
  displayName: 'Installations'
- script:
    npx cypress run --browser chrome --reporter mochawesome --reporter-options "reportFilename=chrome-results"
  displayName: 'Run Tests'
  continueOnError: true
- publish: $(System.DefaultWorkingDirectory)/mochawesome-report
  artifact: Report
  condition: succeededOrFailed()
- publish: $(System.DefaultWorkingDirectory)/cypress/screenshots
  artifact: Screenshots
  condition: failed()

